### ISSUE TITLE
Moderation 

### ISSUE THREAD

**Issue by JonnyTech** [YousefHaggy/TwitterWall#1]
Can you explain how the moderation works?

**Comment by YousefHaggy** [comment]
Sorry I missed this, if you click on the profile picture associated with a tweet, it deletes it. An easy way to handle inappropriate tweets.

**Comment by JonnyTech** [comment]
Thanks - can one edit tweets ie remove offensive language?

**Comment by YousefHaggy** [comment]
Not currently, feel free to make a pull request!
